on: [push]

jobs:
  ossr_new_entry:
    runs-on: ubuntu-latest
    name: A job to upload a new record in the OSSR
    steps:
      - uses: actions/checkout@v2

      - uses: vuillaut/composite-action@main
        with:
          repository_url: https://github.com/vuillaut/test-composite-action
          token: ${{ secrets.SANDBOX_ZENODO_TOKEN }}
          sandbox: True
          
