on: [push]

jobs:
  ossr_new_entry:
    runs-on: ubuntu-latest
    name: git tag
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
          git tag
          
